### ISSUE TITLE
feat: Use prebuilt package to create flatpak package.

### ISSUE THREAD

**Issue by first-storm** [flathub/net.opentabletdriver.OpenTabletDriver#28]
Since we need to update `nupkg` sources whenever **OpenTabletDriver** is updated, using a prebuilt package to create a **Flatpak** package would be a better choice to reduce the difficulty of maintenance.

Please share your opinion on this and discuss whether it is appropriate.

**Comment by jamesbt365** [comment]
If theres any intentions to patch the source directly in this package then building from source *is* better, other than that there isn't really any point to doing so.

Though OpenTabletDriver hasn't released an update in 8+ months yet the sources need updating, usually because of dotnet. Any idea to why those have to be updated because it should just build? Not the most familiar with the way all that works though.

**Comment by first-storm** [comment]
> If theres any intentions to patch the source directly in this package then building from source *is* better, other than that there isn't really any point to doing so.
> 
> Though OpenTabletDriver hasn't released an update in 8+ months yet the sources need updating, usually because of dotnet. Any idea to why those have to be updated because it should just build? Not the most familiar with the way all that works though.

We currently do not have a need to apply additional patches to the source code. If we need to update the dotnet version in the future, it will be very troublesome.

**Comment by jamesbt365** [comment]
I wouldn't say it would be that troublesome, the erogenous CI failures despite no upstream OpenTabletDriver changes is more annoying than having to bump dependencies when actually needed.
